# benchmark/NaiveGeneration/conf/config.yaml

defaults:
  - _self_

debug: False

model:
  path: 'meta-llama/Meta-Llama-3-8B-Instruct' 
  tensor_parallel_size: 1

data:
  dev_dataset_path: '/mnt/raid5/kangjh/downloads/datasets/hotpotqa/dev/dev.json'

params:
  temperature: 0.0
  max_tokens: 512